# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compnumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=200)),
                ('longname', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
