# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0002_auto_20181208_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
